name: Update Checker

permissions:
  actions: write
  contents: write

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * 6

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Latest Tag
      id: getTag
      run: |
        git clone --branch $REPO_BRANCH $REPO_URL .
        echo "latestTag=$(git tag --sort=-creatordate | head -n1)" >> $GITHUB_OUTPUT

    - name: Compare Tag
      id: cacheTag
      uses: actions/cache@main
      with:
        path: .latestTag
        key: OpenWrt-${{ steps.getTag.outputs.latestTag }}

    - name: Save New Tag
      if: steps.cacheTag.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getTag.outputs.latestTag }} | tee .latestTag

    - name: Trigger build
      if: steps.cacheTag.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@main
      with:
        event-type: Source Code Update
        client-payload: '{"version": "stable"}'

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
